import { 
  Heart, 
  Eye, 
  MessageSquare, 
  Share2, 
  Bookmark, 
  BookmarkCheck,
  MoreHorizontal,
  MoreVertical,
  Edit,
  Settings,
  LogOut,
  User,
  FileText,
  Image,
  Book,
  Clock,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Search,
  X,
  Plus,
  Check,
  AlertCircle,
  Info,
  Users,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Upload,
  Download,
  Copy,
  ExternalLink,
  ArrowLeft,
  ArrowRight,
  Home,
  Menu,
  Bell,
  Star,
  Filter,
  Grid,
  List,
  Trash2,
  Archive,
  Flag,
  Lock,
  Unlock,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  RotateCcw,
  RefreshCw,
  Save,
  Loader2,
  Zap,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Target,
  Award,
  Crown,
  Sparkles,
  Lightbulb,
  Palette,
  Code,
  Database,
  Cloud,
  Shield,
  Key,
  Link,
  Globe,
  Wifi,
  Camera,
  Video,
  Mic,
  MicOff,
  Volume,
  Speaker,
  Headphones,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Tv,
  Gamepad2,
  MousePointer,
  Keyboard,
  Printer,
  HardDrive,
  Cpu,
  Battery,
  Power,
  Bluetooth
} from 'lucide-react';

// よく使用されるアイコンをexport
export {
  Heart as HeartIcon,
  Eye as EyeIcon,
  MessageSquare as MessageIcon,
  Share2 as ShareIcon,
  Bookmark as BookmarkIcon,
  BookmarkCheck as BookmarkCheckedIcon,
  MoreHorizontal as DotsHorizontalIcon,
  MoreVertical as DotsVerticalIcon,
  Edit as EditIcon,
  Settings as SettingsIcon,
  LogOut as LogoutIcon,
  User as UserIcon,
  FileText as FileIcon,
  Image as ImageIcon,
  Book as BookIcon,
  Clock as ClockIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  Search as SearchIcon,
  X as CloseIcon,
  Plus as PlusIcon,
  Check as CheckIcon,
  AlertCircle as AlertIcon,
  Info as InfoIcon,
  Users as UsersIcon,
  Mail as EmailIcon,
  Phone as PhoneIcon,
  MapPin as LocationIcon,
  Calendar as CalendarIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  Copy as CopyIcon,
  ExternalLink as ExternalLinkIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Home as HomeIcon,
  Menu as MenuIcon,
  Bell as NotificationIcon,
  Star as StarIcon,
  Filter as FilterIcon,
  Grid as GridIcon,
  List as ListIcon,
  Trash2 as TrashIcon,
  Archive as ArchiveIcon,
  Flag as FlagIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  Volume2 as VolumeIcon,
  VolumeX as MuteIcon,
  Maximize as MaximizeIcon,
  Minimize as MinimizeIcon,
  RotateCcw as UndoIcon,
  RefreshCw as RefreshIcon,
  Save as SaveIcon,
  Loader2 as LoadingIcon,
  Zap as ZapIcon,
  TrendingUp as TrendingIcon,
  BarChart3 as ChartIcon,
  PieChart as PieChartIcon,
  Activity as ActivityIcon,
  Target as TargetIcon,
  Award as AwardIcon,
  Crown as CrownIcon,
  Sparkles as SparklesIcon,
  Lightbulb as IdeaIcon,
  Palette as PaletteIcon,
  Code as CodeIcon,
  Database as DatabaseIcon,
  Cloud as CloudIcon,
  Shield as ShieldIcon,
  Key as KeyIcon,
  Link as LinkIcon,
  Globe as GlobeIcon,
  Wifi as WifiIcon,
  Camera as CameraIcon,
  Video as VideoIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  Volume as VolumeControlIcon,
  Speaker as SpeakerIcon,
  Headphones as HeadphonesIcon,
  Monitor as MonitorIcon,
  Smartphone as PhoneDeviceIcon,
  Tablet as TabletIcon,
  Laptop as LaptopIcon,
  Tv as TvIcon,
  Gamepad2 as GamepadIcon,
  MousePointer as MouseIcon,
  Keyboard as KeyboardIcon,
  Printer as PrinterIcon,
  HardDrive as StorageIcon,
  Cpu as ProcessorIcon,
  Battery as BatteryIcon,
  Power as PowerIcon,
  Bluetooth as BluetoothIcon
};

// アイコンのサイズ定義
export const ICON_SIZES = {
  xs: 'h-3 w-3',
  sm: 'h-4 w-4', 
  md: 'h-5 w-5',
  lg: 'h-6 w-6',
  xl: 'h-8 w-8',
  '2xl': 'h-10 w-10'
} as const;

export type IconSize = keyof typeof ICON_SIZES; 
